import {CONFIG} from './config.js';import {Store} from './store.js';import {Auth} from './auth.js';
const app=document.querySelector('#app'),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let db=Store.load();
const toast=t=>{const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2500)};
function login(){app.innerHTML=`<main class="login"><section class="login-hero"><img src="assets/logo-oficial.png"><h1>Rumbo a Ingeniería 2.0</h1><p class="muted">Núcleo Nube: una sola plataforma para alumnos, familias, docentes y administración.</p></section><section class="login-card"><small style="color:var(--gold)">v${CONFIG.version} · ${CONFIG.mode==='demo'?'Modo demostración':'Nube conectada'}</small><h2>Iniciar sesión</h2><form id="loginForm"><label class="field">Perfil<select name="role"><option value="admin">Administrador</option><option value="teacher">Profesor</option><option value="student">Alumno</option><option value="parent">Padre o tutor</option></select></label><label class="field">Correo (opcional en demo)<input name="email" type="email" placeholder="correo@ejemplo.com"></label><label class="field">PIN de demostración<input name="pin" inputmode="numeric" required placeholder="2607"></label><button class="btn" style="width:100%">Entrar</button></form><p class="muted"><b>Accesos:</b> administrador 2607, profesor 5832, alumno 1001, familia 7001.</p></section></main>`;document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();try{await Auth.signIn(Object.fromEntries(new FormData(e.target)));render()}catch(err){toast(err.message)}}}
const pagesByRole={admin:['dashboard','people','courses','classes','assignments','library','messages','payments','athena','settings'],teacher:['dashboard','courses','classes','assignments','library','messages','athena'],student:['dashboard','courses','classes','assignments','library','messages','athena'],parent:['dashboard','progress','classes','assignments','messages','payments']};
const labels={dashboard:'🏠 Resumen',people:'👥 Personas',courses:'📚 Cursos',classes:'🎥 Clases',assignments:'📝 Tareas',library:'🗂️ Biblioteca',messages:'💬 Mensajes',payments:'💳 Pagos',athena:'🤖 Atenea',settings:'⚙️ Configuración',progress:'📊 Progreso'};
function render(){db=Store.load();const s=Auth.current();if(!s)return login();const pages=pagesByRole[s.role];app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><img src="assets/favicon.png"><div><b>Rumbo a Ingeniería</b><small>Núcleo Nube 2.0</small></div></div><nav class="nav">${pages.map((p,i)=>`<button data-page="${p}" class="${i?'':'active'}">${labels[p]}</button>`).join('')}</nav></aside><main class="main"><header class="topbar"><button class="btn secondary mobile" id="menu">☰</button><div><b id="pageTitle">${labels[pages[0]]}</b><small class="muted" style="display:block">${esc(s.name)} · ${s.role}</small></div><button class="btn secondary" id="logout">Salir</button></header><div class="content">${pages.map((p,i)=>`<section id="${p}" class="page ${i?'':'active'}"></section>`).join('')}</div></main></div><dialog id="modal" class="modal"></dialog>`;
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===b.dataset.page));document.querySelector('#pageTitle').textContent=labels[b.dataset.page];document.querySelector('.sidebar').classList.remove('open')});document.querySelector('#logout').onclick=()=>{Auth.signOut();login()};document.querySelector('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');renderPages(s)}
function metric(label,value){return `<article class="card metric"><span class="muted">${label}</span><b>${value}</b></article>`}
function user(s){return db.profiles.find(p=>p.id===s.id)}
function relatedStudents(s){if(s.role==='student')return [s.id];if(s.role==='parent')return db.links.filter(l=>l.parentId===s.id).map(l=>l.studentId);return db.profiles.filter(p=>p.role==='student').map(p=>p.id)}
function renderPages(s){const ids=relatedStudents(s),u=user(s);const courses=db.courses.filter(c=>s.role==='admin'||(s.role==='teacher'?c.teacherId===s.id:c.studentIds.some(id=>ids.includes(id))));
 if(document.querySelector('#dashboard'))document.querySelector('#dashboard').innerHTML=`<h1>Bienvenido, ${esc(s.name.split(' ')[0])}</h1><p class="muted">Información conectada para tu perfil.</p><div class="grid">${metric('Cursos',courses.length)}${metric('Clases',db.classes.filter(c=>courses.some(x=>x.id===c.courseId)).length)}${metric('Tareas',db.assignments.filter(a=>courses.some(c=>c.id===a.courseId)).length)}${metric('Mensajes',db.messages.filter(m=>m.toId===s.id).length)}<article class="card wide"><h3>Próximas clases</h3><div class="list">${db.classes.filter(c=>courses.some(x=>x.id===c.courseId)).map(c=>`<div class="item"><span><b>${esc(db.courses.find(x=>x.id===c.courseId)?.title)}</b><small>${c.date} · ${c.time} · ${c.duration} min</small></span><span class="badge">${c.status}</span></div>`).join('')||'<p class="muted">Sin clases.</p>'}</div></article><article class="card side"><h3>Estado del sistema</h3><p>✅ Sesión por roles</p><p>✅ Datos compartidos</p><p>✅ Preparado para nube</p><p class="muted">Modo actual: ${CONFIG.mode}</p></article></div>`;
 renderPeople(s);renderCourses(s,courses);renderClasses(s,courses);renderAssignments(s,courses,ids);renderLibrary(s);renderMessages(s);renderPayments(s,ids);renderAthena(s,u);renderSettings(s);renderProgress(s,ids)}
function renderPeople(s){const el=document.querySelector('#people');if(!el)return;el.innerHTML=`<div class="actions"><h1 style="flex:1">Personas</h1><button class="btn" id="addPerson">+ Nuevo usuario</button></div><div class="card"><table class="table"><thead><tr><th>Nombre</th><th>Perfil</th><th>Correo</th><th>Estado</th></tr></thead><tbody>${db.profiles.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.role}</td><td>${esc(p.email)}</td><td>${p.status}</td></tr>`).join('')}</tbody></table></div>`;document.querySelector('#addPerson').onclick=()=>formModal('Nuevo usuario',`<label class="field">Nombre<input name="name" required></label><label class="field">Perfil<select name="role"><option value="student">Alumno</option><option value="teacher">Profesor</option><option value="parent">Padre</option></select></label><label class="field">Correo<input name="email" type="email" required></label><label class="field">PIN<input name="pin" required></label>`,fd=>{db.profiles.push({id:Store.uid(fd.role),...fd,status:'active',progress:0});Store.save(db);render();toast('Usuario creado')})}
function renderCourses(s,courses){const el=document.querySelector('#courses');if(!el)return;el.innerHTML=`<h1>Cursos</h1><div class="grid">${courses.map(c=>`<article class="card side"><span class="badge">${c.subject}</span><h3>${esc(c.title)}</h3><p class="muted">${c.studentIds.length} alumno(s)</p></article>`).join('')||'<p>Sin cursos.</p>'}</div>`}
function renderClasses(s,courses){const el=document.querySelector('#classes');if(!el)return;const list=db.classes.filter(c=>courses.some(x=>x.id===c.courseId));el.innerHTML=`<div class="actions"><h1 style="flex:1">Clases</h1>${['admin','teacher'].includes(s.role)?'<button class="btn" id="addClass">+ Programar</button>':''}</div><div class="card list">${list.map(c=>`<div class="item"><span><b>${esc(db.courses.find(x=>x.id===c.courseId)?.title)}</b><small>${c.date} · ${c.time} · ${c.duration} min</small></span><div class="actions"><span class="badge">${c.status}</span>${c.meetingUrl?`<a class="btn" target="_blank" href="${esc(c.meetingUrl)}">Entrar</a>`:''}</div></div>`).join('')||'<p class="muted">Sin clases.</p>'}</div>`;document.querySelector('#addClass')?.addEventListener('click',()=>formModal('Programar clase',`<label class="field">Curso<select name="courseId">${courses.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}</select></label><label class="field">Fecha<input name="date" type="date" required></label><label class="field">Hora<input name="time" type="time" required></label><label class="field">Duración<input name="duration" type="number" value="60"></label><label class="field">Enlace<input name="meetingUrl" type="url"></label>`,fd=>{const c=db.courses.find(x=>x.id===fd.courseId);db.classes.push({id:Store.uid('class'),...fd,duration:Number(fd.duration),teacherId:c.teacherId,studentIds:c.studentIds,status:'scheduled'});Store.save(db);render()}))}
function renderAssignments(s,courses,ids){const el=document.querySelector('#assignments');if(!el)return;const list=db.assignments.filter(a=>courses.some(c=>c.id===a.courseId));el.innerHTML=`<h1>Tareas</h1><div class="card list">${list.map(a=>{const sub=db.submissions.find(x=>x.assignmentId===a.id&&ids.includes(x.studentId));return `<div class="item"><span><b>${esc(a.title)}</b><small>${esc(a.instructions)} · vence ${a.dueDate}</small></span><span class="badge">${sub?sub.status:'Pendiente'}</span></div>`}).join('')||'<p class="muted">Sin tareas.</p>'}</div>`}
function renderLibrary(s){const el=document.querySelector('#library');if(!el)return;el.innerHTML=`<h1>Biblioteca</h1><div class="grid">${db.resources.map(r=>`<article class="card side"><span class="badge">${r.type}</span><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p><small class="muted">${r.subject} · ${r.level}</small></article>`).join('')}</div>`}
function renderMessages(s){const el=document.querySelector('#messages');if(!el)return;const msgs=db.messages.filter(m=>m.fromId===s.id||m.toId===s.id);el.innerHTML=`<h1>Mensajes</h1><div class="card list">${msgs.map(m=>`<div class="item"><span><b>${m.fromId===s.id?'Enviado':'Recibido'}</b><small>${esc(m.text)}</small></span></div>`).join('')||'<p class="muted">No hay mensajes.</p>'}</div>`}
function renderPayments(s,ids){const el=document.querySelector('#payments');if(!el)return;const list=db.payments.filter(p=>s.role==='admin'||ids.includes(p.studentId));el.innerHTML=`<h1>Pagos</h1><div class="card list">${list.map(p=>`<div class="item"><span><b>${esc(p.concept)}</b><small>${p.date}</small></span><span>$${p.amount} · ${p.status}</span></div>`).join('')||'<p class="muted">Sin pagos.</p>'}</div>`}
function renderAthena(s,u){const el=document.querySelector('#athena');if(!el)return;el.innerHTML=`<h1>Atenea</h1><div class="card athena"><div class="chat" id="chat"><div class="bubble">Hola, ${esc(s.name.split(' ')[0])}. Soy Atenea. Escribe un tema o ejercicio.</div></div><form class="chat-form" id="athenaForm"><input name="q" required placeholder="Ejemplo: explícame las ecuaciones lineales"><button class="btn">Enviar</button></form></div>`;document.querySelector('#athenaForm').onsubmit=e=>{e.preventDefault();const q=new FormData(e.target).get('q');const chat=document.querySelector('#chat');chat.insertAdjacentHTML('beforeend',`<div class="bubble me">${esc(q)}</div><div class="bubble">${esc(athenaAnswer(q))}</div>`);e.target.reset();chat.scrollTop=chat.scrollHeight}}
function athenaAnswer(q){q=q.toLowerCase();if(q.includes('ecuaci'))return 'Primero simplifica ambos lados, reúne las incógnitas, mueve constantes, divide por el coeficiente y verifica sustituyendo.';if(q.includes('newton')||q.includes('fuerza'))return 'Identifica las fuerzas, calcula la fuerza neta y aplica F = m·a. Escribe datos, fórmula, sustitución, resultado y unidades.';if(q.includes('inglés'))return 'Practica cinco oraciones, léelas en voz alta y cambia sujeto, tiempo y complemento.';return 'Indica materia, tema y la parte que te causa dificultad. Te guiaré paso a paso.'}
function renderSettings(s){const el=document.querySelector('#settings');if(!el)return;el.innerHTML=`<h1>Configuración</h1><div class="grid"><article class="card wide"><h3>Conexión a la nube</h3><p class="muted">Edita <code>app/config.js</code> con tu URL y clave pública de Supabase y cambia <code>mode</code> a <code>cloud</code>.</p><p>La base SQL y las políticas de seguridad están en <code>supabase/schema.sql</code>.</p></article><article class="card side"><h3>Respaldo</h3><button class="btn secondary" id="backup">Descargar JSON</button></article></div>`;document.querySelector('#backup').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='rumbo-a-ingenieria-respaldo.json';a.click()}}
function renderProgress(s,ids){const el=document.querySelector('#progress');if(!el)return;el.innerHTML=`<h1>Progreso</h1><div class="grid">${ids.map(id=>{const x=db.profiles.find(p=>p.id===id);return `<article class="card side"><h3>${esc(x?.name)}</h3><b style="font-size:2rem">${x?.progress||0}%</b><p class="muted">Progreso general</p></article>`}).join('')}</div>`}
function formModal(title,fields,onSubmit){const m=document.querySelector('#modal');m.innerHTML=`<form><h2>${title}</h2>${fields}<div class="actions"><button type="button" class="btn secondary" id="cancel">Cancelar</button><button class="btn">Guardar</button></div></form>`;m.showModal();m.querySelector('#cancel').onclick=()=>m.close();m.querySelector('form').onsubmit=e=>{e.preventDefault();onSubmit(Object.fromEntries(new FormData(e.target)));m.close()}}
window.addEventListener('rai:update',()=>{db=Store.load()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
